import type { Fragrance, GiftSet, Ingredient, Testimonial } from './types';

const imagePath = (file: string) => `/src/assets/images/${file}`;

export const fragrances: Fragrance[] = [
  {
    id: 'oud-noir',
    name: 'Oud Noir',
    arabicName: 'عود نوار',
    type: 'Extrait de Parfum',
    typeAr: 'مستخلص عطر فاخر',
    notes: ['Agarwood', 'Amber', 'Musk'],
    notesAr: ['العود الثمين', 'العنبر المتوهج', 'المسك الفاخر'],
    description: 'A deep and magnetic composition of rare oud wood, glowing amber, and soft musk.',
    descriptionAr: 'تركيبة عميقة وساحرة من خشب العود النادر، العنبر المتوهج، والمسك المخملي الدافئ.',
    price: 420,
    image: imagePath('1.png'),
    volume: '100ml',
    rating: 4.9,
    reviewsCount: 148,
    story: 'Rare oud wood, glowing amber, and soft musk create a fragrance of quiet power.',
    storyAr: 'مزيج فاخر من العود والعنبر والمسك يمنح حضوراً هادئاً وقوياً.',
    isNew: true,
  },
  {
    id: 'lavande-de-nuit',
    name: 'Lavande de Nuit',
    arabicName: 'لافندر دي نوي',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Lavender', 'Bergamot', 'White Musk'],
    notesAr: ['اللافندر الفرنسي', 'البرغموت الإيطالي', 'المسك الأبيض النقي'],
    description: 'A calm nocturnal blend where aromatic lavender meets bright bergamot and clean white musk.',
    descriptionAr: 'مزيج ليلي هادئ يلتقي فيه الخزامى العطري مع البرغموت المشرق والمسك الأبيض النقي.',
    price: 340,
    image: imagePath('2.png'),
    volume: '100ml',
    rating: 4.7,
    reviewsCount: 92,
    story: 'A serene lavender trail brightened by citrus and softened with white musk.',
    storyAr: 'نفحات لافندر هادئة يضيئها البرغموت ويكملها المسك الأبيض.',
  },
  {
    id: 'rose-eternelle',
    name: 'Rose Éternelle',
    arabicName: 'روز إيتيرنيل',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Damask Rose', 'Peony', 'Soft Amber'],
    notesAr: ['الورد الدمشقي', 'زهور الفاونيا', 'العنبر اللطيف'],
    description: 'A velvety floral fragrance built around rich rose petals, soft peony, and warm amber.',
    descriptionAr: 'عطر زهري مخملي مبني حول بتلات الورد الدمشقي الغني، زهور الفاونيا الناعمة، والعنبر الدافئ.',
    price: 360,
    image: imagePath('4.png'),
    volume: '100ml',
    rating: 4.8,
    reviewsCount: 114,
    story: 'A romantic rose composition with a warm amber finish.',
    storyAr: 'تركيبة ورد رومانسية تنتهي بدفء عنبري ناعم.',
  },
  {
    id: 'jasmin-blanc',
    name: 'Jasmin Blanc',
    arabicName: 'ياسمين بلان',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Jasmine', 'Neroli', 'Sandalwood'],
    notesAr: ['الياسمين الملكي', 'النيرولي المشرق', 'خشب الصندل الكريمي'],
    description: 'A luminous white floral scent with jasmine, neroli freshness, and a creamy sandalwood finish.',
    descriptionAr: 'رائحة زهرية بيضاء ناصعة ومضيئة تجمع بين الياسمين الملكي ونقاء النيرولي مع قاعدة الصندل الكريمية.',
    price: 350,
    image: imagePath('7.png'),
    volume: '100ml',
    rating: 4.6,
    reviewsCount: 86,
    story: 'Luminous jasmine and neroli rest on smooth sandalwood.',
    storyAr: 'ياسمين مضيء ونيرولي منعش على قاعدة من خشب الصندل الناعم.',
  },
  {
    id: 'safran-dor',
    name: "Safran d'Or",
    arabicName: 'زعفران دور',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Saffron', 'Amber', 'Cedarwood'],
    notesAr: ['خيوط الزعفران', 'العنبر النقي', 'خشب الأرز'],
    description: 'A radiant and spicy composition of saffron threads, glowing amber, and dry cedarwood.',
    descriptionAr: 'تركيبة متوهجة مفعمة بالتوابل الراقية من خيوط الزعفران الأحمر، العنبر الدافئ، وخشب الأرز الجاف.',
    price: 390,
    image: imagePath('5.png'),
    volume: '100ml',
    rating: 4.9,
    reviewsCount: 121,
    story: 'Saffron and amber bring a luminous, confident warmth.',
    storyAr: 'زعفران وعنبر يمنحان العطر دفئاً مشرقاً وحضوراً واثقاً.',
  },
  {
    id: 'encens-royal',
    name: 'Encens Royal',
    arabicName: 'بخور ملكي',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Frankincense', 'Myrrh', 'Vanilla'],
    notesAr: ['اللبان العربي الفاخر', 'المر الغامض', 'الفانيليا المدخنة'],
    description: 'A mystical incense fragrance with golden frankincense resin, smoky myrrh, and smooth vanilla.',
    descriptionAr: 'عطر بخوري ساحر يحوي دموع اللبان العربي الذهبي، غموض المر المدخن، ونعومة الفانيليا الكريمية.',
    price: 400,
    image: imagePath('6.png'),
    volume: '100ml',
    rating: 4.8,
    reviewsCount: 103,
    story: 'Frankincense and myrrh unfold into a rich, meditative trail.',
    storyAr: 'اللبان والمر ينسابان في هالة عطرية عميقة وتأملية.',
  },
  {
    id: 'santal-ambre',
    name: 'Santal Ambré',
    arabicName: 'صندل عنبر',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Sandalwood', 'Tonka', 'Soft Musk'],
    notesAr: ['خشب الصندل الكريمي', 'حبوب التونكا الدافئة', 'المسك المخملي'],
    description: 'A smooth woody fragrance of creamy sandalwood, warm tonka, and velvety musk.',
    descriptionAr: 'عطر خشبي ناعم ودافئ من خشب الصندل الكريمي الفاخر، حبوب التونكا، والمسك المخملي الرقيق.',
    price: 380,
    image: imagePath('3.png'),
    volume: '100ml',
    rating: 4.9,
    reviewsCount: 112,
    story: 'Creamy sandalwood, warm tonka, and soft musk in a polished woody scent.',
    storyAr: 'خشب صندل كريمي وتونكا دافئة ومسك ناعم في تركيبة خشبية راقية.',
  },
];

export const ingredients: Ingredient[] = [
  { id: 'oud', name: 'Oud', nameAr: 'العود', description: 'Dark, resinous, and unforgettable—the soul of Arabian perfumery.', descriptionAr: 'داكن وراتنجي ولا ينسى، روح العطور العربية.' },
  { id: 'saffron', name: 'Saffron', nameAr: 'الزعفران', description: 'Golden warmth with a luminous, refined spice.', descriptionAr: 'دفء ذهبي مشرق بلمسة من التوابل الفاخرة.' },
  { id: 'rose', name: 'Rose', nameAr: 'الورد', description: 'A velvety floral crown of purity and romance.', descriptionAr: 'تاج زهري مخملي من النقاء والرومانسية.' },
  { id: 'jasmine', name: 'Jasmine', nameAr: 'الياسمين', description: 'A luminous white floral note of effortless elegance.', descriptionAr: 'نفحة زهرية بيضاء مضيئة من الأناقة الهادئة.' },
  { id: 'frankincense', name: 'Frankincense', nameAr: 'اللبان', description: 'Ancient resin, sacred smoke, and meditative depth.', descriptionAr: 'راتنج عتيق وبخور هادئ وعمق تأملي.' },
  { id: 'sandalwood', name: 'Sandalwood', nameAr: 'خشب الصندل', description: 'Creamy, warm, and structured wood tones.', descriptionAr: 'خشب كريمي دافئ وغني.' },
  { id: 'musk', name: 'Musk', nameAr: 'المسك', description: 'A velvety foundation that prolongs every scent story.', descriptionAr: 'قاعدة مخملية تطيل حكاية كل عطر.' },
];

export const giftSets: GiftSet[] = [
  {
    id: 'oud-discovery',
    name: 'The Oud Discovery Set',
    nameAr: 'مجموعة اكتشاف العود',
    description: 'A travel-sized introduction to the house’s richest oud and amber compositions.',
    descriptionAr: 'مجموعة سفر تعرّفك على أغنى تركيبات العود والعنبر في الدار.',
    price: 580,
    items: ['Oud Noir', "Safran d'Or", 'Encens Royal'],
    itemsAr: ['عود نوار', 'زعفران دور', 'بخور ملكي'],
    image: imagePath('1.png'),
  },
  {
    id: 'floral-collection',
    name: 'The Floral Collection Set',
    nameAr: 'مجموعة الزهور',
    description: 'A delicate selection of jasmine, rose, and lavender fragrances.',
    descriptionAr: 'مجموعة رقيقة من عطور الياسمين والورد واللافندر.',
    price: 520,
    items: ['Rose Éternelle', 'Jasmin Blanc', 'Lavande de Nuit'],
    itemsAr: ['روز إيتيرنيل', 'ياسمين بلان', 'لافندر دي نوي'],
    image: imagePath('4.png'),
  },
  {
    id: 'arabian-essentials',
    name: 'The Arabian Essentials Set',
    nameAr: 'مجموعة الأساسيات العربية',
    description: 'A warm collection of sandalwood, incense, and signature oud.',
    descriptionAr: 'مجموعة دافئة من الصندل والبخور والعود المميز.',
    price: 650,
    items: ['Santal Ambré', 'Encens Royal', 'Oud Noir'],
    itemsAr: ['صندل عنبر', 'بخور ملكي', 'عود نوار'],
    image: imagePath('3.png'),
  },
];

export const testimonials: Testimonial[] = [
  { id: 't1', quote: 'Rich, sophisticated, and beautifully long-lasting. Oud Noir has become my signature.', quoteAr: 'عطر غني وراقٍ وثابت بشكل مذهل. أصبح عود نوار عطري المميز.', author: 'Ahmed R.', authorAr: 'أحمد ر.', location: 'Dubai', locationAr: 'دبي', rating: 5 },
  { id: 't2', quote: 'The presentation feels as luxurious as the fragrance itself.', quoteAr: 'التقديم فخم مثل العطر نفسه.', author: 'Sara M.', authorAr: 'سارة م.', location: 'Abu Dhabi', locationAr: 'أبوظبي', rating: 5 },
  { id: 't3', quote: "Safran d'Or is warm, elegant, and unlike anything else I have worn.", quoteAr: 'زعفران دور دافئ وراقٍ ومختلف عن أي عطر ارتديته.', author: 'Noor A.', authorAr: 'نور أ.', location: 'Sharjah', locationAr: 'الشارقة', rating: 5 },
];
