import { Fragrance, Ingredient, GiftSet, Testimonial } from './types';

export const fragrances: Fragrance[] = [
  {
    id: 'oud-noir',
    name: 'Oud Noir',
    arabicName: 'عود نوار',
    type: 'Extrait de Parfum',
    typeAr: 'مستخلص عطر فاخر',
    notes: ['Agarwood', 'Amber', 'Musk'],
    notesAr: ['العود الثمين', 'العنبر المتوهج', 'المسك الفاخر'],
    description: 'A deep and magnetic composition of rare oud wood, glowing amber, and soft musk.',
    descriptionAr: 'تركيبة عميقة وساحرة من خشب العود النادر، العنبر المتوهج، والمسك المخملي الدافئ.',
    price: 420,
    image: '/src/assets/images/oud_noir_1782593272388.jpg',
    volume: '100ml',
    rating: 4.9,
    reviewsCount: 148,
    story: 'Oud Noir is the crown jewel of Al Faisal. Inspired by the dense Arabian nights, this Extrait de Parfum captures the mysterious grandeur of pure Indian agarwood combined with warm, glowing Baltic amber. It represents unparalleled presence, power, and prestige.',
    storyAr: 'عطر عود نوار هو جوهرة التاج لدى الفصيل. مستوحى من ليالي شبه الجزيرة العربية الغامضة والمهيبة، يجسد هذا المستخلص الفخامة المطلقة للعود الهندي النادر الممزوج بدفء العنبر البلطي المتقد. إنه يمثل الحضور اللامتناهي والقوة والهيبة.',
    isNew: true
  },
  {
    id: 'lavande-de-nuit',
    name: 'Lavande de Nuit',
    arabicName: 'لافندر دي نوي',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Lavender', 'Bergamot', 'White Musk'],
    notesAr: ['اللافندر الفرنسي', 'البرغموت الإيطالي', 'المسك الأبيض النقي'],
    description: 'A calm nocturnal blend where aromatic lavender meets bright bergamot and clean white musk.',
    descriptionAr: 'مزيج ليلي هادئ يلتقي فيه الخزامى العطري مع البرغموت المشرق والمسك الأبيض النقي.',
    price: 340,
    image: '/src/assets/images/lavande_de_nuit_1782593293337.jpg',
    volume: '100ml',
    rating: 4.7,
    reviewsCount: 92,
    story: 'Lavande de Nuit is a poetic expression of the cooling desert breeze under a star-studded sky. French high-altitude lavender is paired with the sparkling freshness of Calabrian bergamot, resting on a serene, powdery base of luxurious white musk.',
    storyAr: 'عطر لافندر دي نوي هو تعبير شاعري عن نسيم الصحراء العليل تحت سماء مرصعة بالنجوم. يمتزج الخزامى الفرنسي الجبلي مع حيوية البرغموت الكالابري، ليستقر العطر على قاعدة وادعة ومخملية من المسك الأبيض الفاخر.'
  },
  {
    id: 'rose-eternelle',
    name: 'Rose Éternelle',
    arabicName: 'روز إيتيرنيل',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Damask Rose', 'Peony', 'Soft Amber'],
    notesAr: ['الورد الدمشقي', 'زهور الفاونيا', 'العنبر اللطيف'],
    description: 'A velvety floral fragrance built around rich rose petals, soft peony, and warm amber.',
    descriptionAr: 'عطر زهري مخملي مبني حول بتلات الورد الدمشقي الغني، زهور الفاونيا الناعمة، والعنبر الدافئ.',
    price: 360,
    image: '/src/assets/images/rose_eternelle_1782593306369.jpg',
    volume: '100ml',
    rating: 4.8,
    reviewsCount: 114,
    story: 'This fragrance pays homage to the legendary Taif rose fields of the East. Delicate yet incredibly persistent, Rose Éternelle unfolds layers of blooming Damask rose, refreshed by crisp white peony, before settling into a warm, sensual amber embrace.',
    storyAr: 'يقدم هذا العطر تحية إجلال لحقول ورد الطائف الشرقية الأسطورية. روز إيتيرنيل، رقيق ولكنه ثابت للغاية، يكشف عن طبقات من الورد الدمشقي المتفتح المحاط ببتلات الفاونيا، مستقراً في دفء عنبري آسر وساحر.'
  },
  {
    id: 'jasmin-blanc',
    name: 'Jasmin Blanc',
    arabicName: 'ياسمين بلان',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Jasmine', 'Neroli', 'Sandalwood'],
    notesAr: ['الياسمين الملكي', 'النيرولي المشرق', 'خشب الصندل الكريمي'],
    description: 'A luminous white floral scent with jasmine, neroli freshness, and a creamy sandalwood finish.',
    descriptionAr: 'رائحة زهرية بيضاء ناصعة ومضيئة تجمع بين الياسمين الملكي ونقاء النيرولي مع قاعدة الصندل الكريمية.',
    price: 350,
    image: '/src/assets/images/jasmin_blanc_1782593319929.jpg',
    volume: '100ml',
    rating: 4.6,
    reviewsCount: 86,
    story: 'Jasmin Blanc captures the sun-drenched gardens of the Arabian palaces. Luminous hand-picked royal jasmine Sambac leads this fragrance, accompanied by the uplifting green nuances of orange blossom neroli, and structured by the absolute creaminess of East Indian sandalwood.',
    storyAr: 'ياسمين بلان يجسد حدائق القصور العربية المغمورة بأشعة الشمس الذهبية. يتصدر هذا العطر ياسمين السامباك الملكي المقطوف بعناية، يرافقه النيرولي المنعش، ومثبت برائحة خشب الصندل الهندي الشرقي الفاخر.'
  },
  {
    id: 'safran-dor',
    name: 'Safran d\'Or',
    arabicName: 'زعفران دور',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Saffron', 'Amber', 'Cedarwood'],
    notesAr: ['خيوط الزعفران', 'العنبر النقي', 'خشب الأرز'],
    description: 'A radiant and spicy composition of saffron threads, glowing amber, and dry cedarwood.',
    descriptionAr: 'تركيبة متوهجة مفعمة بالتوابل الراقية من خيوط الزعفران الأحمر، العنبر الدافئ، وخشب الأرز الجاف.',
    price: 390,
    image: '/src/assets/images/safran_dor_1782593331365.jpg',
    volume: '100ml',
    rating: 4.9,
    reviewsCount: 121,
    story: 'Saffron, known as the red gold of the East, is the beating heart of Safran d\'Or. We capture its exquisite, earthy spice and elevate it with radiant liquid amber and the structural elegance of Atlas mountain cedarwood, creating a trail of warmth and authority.',
    storyAr: 'الزعفران، المعروف بالذهب الأحمر في الشرق، هو القلب النابض لعطر زعفران دور. نلتقط عبيره الترابي الدافئ ونرتقي به مع العنبر السائل الفاخر وهيبة خشب أرز الأطلس، لنبتكر هالة من الدفء والجاذبية الاستثنائية.'
  },
  {
    id: 'encens-royal',
    name: 'Encens Royal',
    arabicName: 'بخور ملكي',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Frankincense', 'Myrrh', 'Vanilla'],
    notesAr: ['اللبان العربي الفاخر', 'المر الغامض', 'الفانيليا المدخنة'],
    description: 'A mystical incense fragrance with golden frankincense resin, smoky myrrh, and smooth vanilla.',
    descriptionAr: 'عطر بخوري ساحر يحوي دموع اللبان العربي الذهبي، غموض المر المدخن، ونعومة الفانيليا الكريمية.',
    price: 400,
    image: '/src/assets/images/encens_royal_1782593342564.jpg',
    volume: '100ml',
    rating: 4.8,
    reviewsCount: 103,
    story: 'Encens Royal is inspired by the ancient frankincense trading routes crossing Oman and Southern Arabia. It is a deeply spiritual, meditative scent featuring pure golden frankincense resin and balsamic myrrh, balanced expertly by a rich, luxurious absolute of Madagascar vanilla.',
    storyAr: 'بخور ملكي مستوحى من دروب تجارة البخور التاريخية القديمة عبر عُمان وجنوب الجزيرة العربية. إنه عطر روحي عميق يتميز بدموع اللبان الذهبي وبلسم المر، ويتوازن باحترافية مع الفانيليا المدخنة الفاخرة.'
  },
  {
    id: 'santal-ambre',
    name: 'Santal Ambré',
    arabicName: 'صندل عنبر',
    type: 'Eau de Parfum',
    typeAr: 'ماء عطر',
    notes: ['Sandalwood', 'Tonka', 'Soft Musk'],
    notesAr: ['خشب الصندل الكريمي', 'حبوب التونكا الدافئة', 'المسك المخملي'],
    description: 'A smooth woody fragrance of creamy sandalwood, warm tonka, and velvety musk.',
    descriptionAr: 'عطر خشبي ناعم ودافئ من خشب الصندل الكريمي الفاخر، حبوب التونكا، والمسك المخملي الرقيق.',
    price: 380,
    image: '/src/assets/images/santal_ambre_1782593354818.jpg',
    volume: '100ml',
    rating: 4.9,
    reviewsCount: 112,
    story: 'Santal Ambré is a masterclass in olfactory smooth. Creamy Mysore sandalwood takes center stage, enveloped in the almond-like warmth of roasted South American tonka bean, and wrapped in a soft, cloud-like envelope of premium white musk.',
    storyAr: 'عطر صندل عنبر يمثل الرقي والنعومة المطلقة. يحتل خشب صندل مايسور الكريمي الفاخر مركز الصدارة، معانقاً حبوب التونكا الدافئة ذات العبير الشبيه باللوز، ومغلفاً بهالة سحابية ناعمة من المسك الفاخر.'
  }
];

export const ingredients: Ingredient[] = [
  {
    id: 'oud',
    name: 'Oud',
    nameAr: 'العود',
    description: 'Dark, resinous, and unforgettable—the soul of Arabian perfumery.',
    descriptionAr: 'داكن، راتنجي، ولا ينسى - روح العطور العربية الأصيلة.'
  },
  {
    id: 'saffron',
    name: 'Saffron',
    nameAr: 'الزعفران',
    description: 'Golden warmth with a luminous, refined spice.',
    descriptionAr: 'دفء ذهبي مشرق مع لمسة من التوابل الفاخرة النادرة.'
  },
  {
    id: 'rose',
    name: 'Rose',
    nameAr: 'الورد',
    description: 'A velvety floral crown representing unmatched purity and romance.',
    descriptionAr: 'تاج زهري مخملي يمثل النقاء المطلق والشاعرية الفاخرة.'
  },
  {
    id: 'jasmine',
    name: 'Jasmine',
    nameAr: 'الياسمين',
    description: 'A luminous white floral scent reflecting palatial luxury.',
    descriptionAr: 'عبير زهري أبيض ناصع ومشرق يعكس فخامة القصور الملكية.'
  },
  {
    id: 'frankincense',
    name: 'Frankincense',
    nameAr: 'اللبان',
    description: 'Ancient resin, sacred smoke, and quiet meditative depth.',
    descriptionAr: 'راتنج عتيق، بخور مقدس، وعمق تأملي هادئ يتجاوز الزمن.'
  },
  {
    id: 'sandalwood',
    name: 'Sandalwood',
    nameAr: 'خشب الصندل',
    description: 'Creamy, warm, and structurally rich wood tones.',
    descriptionAr: 'خشب كريمي، دافئ، وثرى البنية يضفي ثباتاً ورقياً فريداً.'
  },
  {
    id: 'musk',
    name: 'Musk',
    nameAr: 'المسك',
    description: 'A velvety foundation that unites and prolongs every scent story.',
    descriptionAr: 'قاعدة مخملية توحد النفحات العطرية وتطيل من حكايتها الفاتنة.'
  }
];

export const giftSets: GiftSet[] = [
  {
    id: 'oud-discovery',
    name: 'The Oud Discovery Set',
    nameAr: 'مجموعة اكتشاف العود الفاخرة',
    description: 'A collection of four travel-sized Oud masterpieces packaged in a luxurious black and gold foil casing.',
    descriptionAr: 'مجموعة حصرية تضم أربع تحف عطرية صغيرة الحجم مبنية حول العود في علبة سوداء مخملية مطعمة بالذهب.',
    price: 580,
    items: ['Oud Noir (30ml)', 'Safran d\'Or (30ml)', 'Encens Royal (30ml)', 'Luxury Scent Blotters'],
    itemsAr: ['عود نوار (30 مل)', 'زعفران دور (30 مل)', 'بخور ملكي (30 مل)', 'أوراق تجربة فاخرة'],
    image: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=600&h=450' // elegant black box placeholder
  },
  {
    id: 'floral-collection',
    name: 'The Floral Collection Set',
    nameAr: 'مجموعة الزهور الأبدية',
    description: 'Our finest delicate white and damask rose floral creations. The ultimate romantic gift.',
    descriptionAr: 'أرقى إبداعاتنا الزهرية من الورد الدمشقي والياسمين الأبيض لتقدم الهدية الرومانسية الأكثر فخامة.',
    price: 520,
    items: ['Rose Éternelle (30ml)', 'Jasmin Blanc (30ml)', 'Lavande de Nuit (30ml)', 'Velvet Pouch'],
    itemsAr: ['روز إيتيرنيل (30 مل)', 'ياسمين بلان (30 مل)', 'لافندر دي نوي (30 مل)', 'حقيبة مخملية فاخرة'],
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=600&h=450' // luxury packaging mockup
  },
  {
    id: 'arabian-essentials',
    name: 'The Arabian Essentials Set',
    nameAr: 'مجموعة المقتنيات العربية الأساسية',
    description: 'A full olfactory tour of Arabian scent culture featuring premium oils, a sandalwood tablet, and fragrances.',
    descriptionAr: 'جولة عطرية متكاملة في ثقافة العطور العربية العتيقة، تضم أدهاناً نقية، رقائق صندل عطرية وعطوراً فاخرة.',
    price: 650,
    items: ['Santal Ambré (50ml)', 'Oud Noir Oil (12ml)', 'Handpicked Oud Chips', 'Brass Incense Burner'],
    itemsAr: ['صندل عنبر (50 مل)', 'دهن عود نوار (12 مل)', 'رقائق عود طبيعية مختارة', 'مبخرة نحاسية عتيقة'],
    image: 'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&q=80&w=600&h=450' // rich Middle Eastern display
  }
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    quote: 'Rich, sophisticated, and beautifully long-lasting. Oud Noir has become my signature and presence in every room.',
    quoteAr: 'عطر غني، راقٍ، وثابت بشكل مذهل. لقد أصبح عطر عود نوار هويتي وحضوري الطاغي في كل مجلس.',
    author: 'Ahmed R.',
    authorAr: 'أحمد الرميثي',
    location: 'Dubai',
    locationAr: 'دبي',
    rating: 5
  },
  {
    id: 't2',
    quote: 'The presentation feels as luxurious as the fragrance itself. Unboxing is a grand experience suitable for royals.',
    quoteAr: 'التقديم فخم ومبهر للغاية تماماً مثل العطر نفسه. إن فتح الصندوق تجربة مهيبة تليق بالملوك.',
    author: 'Sara M.',
    authorAr: 'سارة المنصوري',
    location: 'Abu Dhabi',
    locationAr: 'أبوظبي',
    rating: 5
  },
  {
    id: 't3',
    quote: 'Safran d’Or is warm, elegant, and unlike anything else I have ever worn. It commands absolute respect.',
    quoteAr: 'عطر زعفران دور دافئ وراقٍ ومختلف عن أي شيء ارتديته من قبل. إنه يفرض هيبة حقيقية وحضوراً استثنائياً.',
    author: 'Noor A.',
    authorAr: 'نور القاسمي',
    location: 'Sharjah',
    locationAr: 'الشارقة',
    rating: 5
  }
];

export const translations = {
  en: {
    brand: 'AL FAISAL',
    brandSubtitle: 'PERFUMES',
    slogan: 'Essence Crafted for Presence.',
    tagline: 'THE ART OF ARABIAN PERFUMERY',
    description: 'Discover a collection of refined fragrances inspired by the most treasured ingredients of the East.',
    explore: 'Explore the Collection',
    discoverOud: 'Discover Oud Noir',
    signatureCollection: 'THE SIGNATURE COLLECTION',
    signatureSubtitle: 'Seven expressions of depth, elegance, and timeless scent.',
    fromNature: 'FROM NATURE TO MEMORY',
    craftedInUae: 'CRAFTED IN THE UAE',
    brandStoryText: 'AL FAISAL Perfumes brings together the richness of Arabian fragrance traditions and contemporary refinement. Every composition is designed to leave a lasting impression—layered, elegant, and made for moments that matter.',
    ourStoryBtn: 'Our Story',
    findSignature: 'FIND YOUR SIGNATURE SCENT',
    quizText: 'Answer a few simple questions and discover the fragrance that matches your presence.',
    startQuizBtn: 'Start Your Scent Journey',
    artOfGifting: 'THE ART OF GIFTING',
    exploreGiftSets: 'Explore Gift Sets',
    wornRemembered: 'WORN. REMEMBERED.',
    enterHouse: 'ENTER THE HOUSE OF AL FAISAL',
    newsletterText: 'Receive early access to new creations, limited editions, and private offers.',
    emailPlaceholder: 'Enter your email address',
    joinMaison: 'Join the Maison',
    viewFragrance: 'View Fragrance',
    addToBag: 'Add to Bag',
    addedToBag: 'Added!',
    cartTitle: 'Shopping Bag',
    cartEmpty: 'Your shopping bag is empty.',
    checkout: 'Proceed to Checkout',
    total: 'Total',
    subtotal: 'Subtotal',
    freeShipping: 'Free Premium Express Shipping inside GCC',
    aed: 'AED',
    quickView: 'Quick View',
    close: 'Close',
    notes: 'Scent Notes',
    rating: 'Rating',
    storyTitle: 'The Scent Story',
    size: 'Size',
    quantity: 'Quantity',
    whatsappMessage: 'Hello Al Faisal Perfumes, I would like to inquire about your fine fragrances.',
    whatsappChatTitle: 'Chat with our Fragrance Advisor',
    whatsappOnline: 'Advisor is online',
    startChat: 'Start WhatsApp Chat',
    searchPlaceholder: 'Search fragrances by name or notes...',
    noResults: 'No fragrances found matching your search.',
    resultsFound: 'Fragrances matching your search:',
    language: 'Language',
    giftSetIncludes: 'Includes:',
    quizTitle: 'Discover Your Signature',
    quizQuestion1: 'Which environment resonates most with your spirit?',
    quizQuestion2: 'How would you describe the aura you wish to project?',
    quizQuestion3: 'What olfactory note holds the key to your memory?',
    next: 'Next Question',
    back: 'Back',
    submitQuiz: 'Reveal My Signature',
    quizResultTitle: 'Your Olfactory Signature is',
    retakeQuiz: 'Take the Quiz Again',
    successSubscribe: 'Welcome to the House of Al Faisal. Subscription successful.',
  },
  ar: {
    brand: 'آل فيصل',
    brandSubtitle: 'للعطور',
    slogan: 'جوهرٌ صِيغَ ليمنحَكَ حُضوراً.',
    tagline: 'فنون العطور العربية الراقية',
    description: 'اكتشف مجموعة من العطور الراقية والمنتقاة، المستوحاة من أثمن وأندر مكونات الشرق الساحر.',
    explore: 'استكشف المجموعة',
    discoverOud: 'اكتشف عود نوار',
    signatureCollection: 'المجموعة الحصرية والخاصة',
    signatureSubtitle: 'سبعة تعبيرات عطرية تجسد العمق، الأناقة والخلود.',
    fromNature: 'من الطبيعة إلى الذاكرة',
    craftedInUae: 'صُنع بكل فخر في الإمارات',
    brandStoryText: 'تجمع عطور آل فيصل بين ثراء وعراقة تقاليد العطور العربية والنعومة المعاصرة المبتكرة. صممت كل توليفة تترك انطباعاً أبدياً لا يُمحى—عطور متدرجة الطبقات، أنيقة ومصنوعة للحظات الاستثنائية التي تهمك.',
    ourStoryBtn: 'قصتنا الكاملة',
    findSignature: 'ابحث عن بصمتك العطرية الخاصة',
    quizText: 'أجب عن بضعة أسئلة بسيطة واكتشف العطر الاستثنائي الذي يتوافق مع حضورك وهيبتك.',
    startQuizBtn: 'ابدأ رحلة الاكتشاف العطري',
    artOfGifting: 'فن تقديم الهدايا الراقية',
    exploreGiftSets: 'استكشف مجموعات الهدايا',
    wornRemembered: 'يُرتدى.. ليبقى في الذاكرة.',
    enterHouse: 'انضم إلى دار آل فيصل للعطور',
    newsletterText: 'احصل على وصول حصري ومبكر لابتكاراتنا الجديدة، الإصدارات المحدودة والعروض الخاصة والخاصة جداً.',
    emailPlaceholder: 'أدخل بريدك الإلكتروني هنا',
    joinMaison: 'انضم لدارنا الفاخرة',
    viewFragrance: 'تفاصيل العطر',
    addToBag: 'أضف لحقيبة التسوق',
    addedToBag: 'تمت الإضافة!',
    cartTitle: 'حقيبة التسوق',
    cartEmpty: 'حقيبة التسوق الخاصة بك فارغة.',
    checkout: 'الذهاب لإتمام الطلب',
    total: 'الإجمالي',
    subtotal: 'المجموع الفرعي',
    freeShipping: 'شحن سريع ومجاني لجميع دول مجلس التعاون الخليجي',
    aed: 'د.إ',
    quickView: 'عرض سريع',
    close: 'إغلاق',
    notes: 'النفحات والروائح العطرية',
    rating: 'التقييم',
    storyTitle: 'قصة وإلهام العطر',
    size: 'الحجم',
    quantity: 'الكمية',
    whatsappMessage: 'مرحباً عطور آل فيصل، أرغب في الاستفسار عن عطوركم الفاخرة والطلب مباشرة.',
    whatsappChatTitle: 'تحدث مع مستشار العطور الخاص بنا',
    whatsappOnline: 'المستشار متصل بالإنترنت الآن',
    startChat: 'بدء المحادثة عبر واتساب',
    searchPlaceholder: 'ابحث عن عطورك المفضلة باسمها أو بنفحاتها...',
    noResults: 'لم نجد عطوراً تطابق بحثك الحالي.',
    resultsFound: 'العطور المطابقة لبحثك هي:',
    language: 'اللغة',
    giftSetIncludes: 'تتضمن المجموعة:',
    quizTitle: 'اكتشف بصمتك العطرية',
    quizQuestion1: 'أي الأجواء والبيئات تعكس روحك وتلهمك أكثر؟',
    quizQuestion2: 'كيف تصف الهالة أو الطابع الذي تود تركه في الأذهان؟',
    quizQuestion3: 'أي النفحات العطرية تلامس ذاكرتك وتجذبك بشدة؟',
    next: 'السؤال التالي',
    back: 'السابق',
    submitQuiz: 'اكشف عن بصمتي العطرية',
    quizResultTitle: 'البصمة العطرية التي تلائم حضورك هي',
    retakeQuiz: 'إعادة إجراء الاختبار',
    successSubscribe: 'مرحباً بك في دار آل فيصل للعطور. تم الاشتراك بنجاح.',
  }
};
